### ISSUE TITLE
网易音乐 下载失败: remote server was unable to handle the request 请重试。

### ISSUE THREAD

**Issue by guoyn90** [WooMaiLabs/WMBot-Docs#3]

**Comment by guoyn90** [comment]
大大，不能用了么

**Comment by zbn297427669** [comment]
遇到了相同的问题.

**Comment by guoyn90** [comment]
棒棒的~~

**Comment by shanlin2dltk** [comment]
any updates on this issue?

**Comment by zbn297427669** [comment]
2022-3-10 目前查看此功能已修复

**Comment by WooMai** [comment]
自 V3 更新以来，此问题已过时，关闭此 Issue。
This issue is outdated since V3, closing this issue.

此 Repo 的 Issue 不受监控。请邮件联系 xiaomai@wmlabs.net 以便快速处理，感谢反馈。
Issues for this repository are not monitored. Please contact xiaomai@wmlabs.net for a quick response. Thanks for the feedback.
