### ISSUE TITLE
下载失败: bad HTTP response 请重试。

### ISSUE THREAD

**Issue by shanlin2dltk** [WooMaiLabs/WMBot-Docs#5]
In the last 2 weeks, I keep getting 下载失败: bad HTTP response 请重试。

Even after updating Telegram to the latest, it still gives error.  Can this be fixed?  Thanks!

**Comment by zbn297427669** [comment]
今天我也遇到了.

**Comment by marshal60** [comment]
我遇到的情况很奇怪，某些歌会有这个问题，例如《上海滩》

**Comment by shanlin2dltk** [comment]
Me too!  Some songs have this problem.  But it tends to have more problems lately....

**Comment by WooMai** [comment]
自 V3 更新以来，此问题已过时，关闭此 Issue。
This issue is outdated since V3, closing this issue.

此 Repo 的 Issue 不受监控。请邮件联系 xiaomai@wmlabs.net 以便快速处理，感谢反馈。
Issues for this repository are not monitored. Please contact xiaomai@wmlabs.net for a quick response. Thanks for the feedback.
