### ISSUE TITLE
Download error message: Song is not available

### ISSUE THREAD

**Issue by shanlin2dltk** [WooMaiLabs/WMBot-Docs#6]
Since 3.0+ upgrade, I always got "Song is not available" message.  The search is successful, and it displays a list of songs.  But once a song is picked, it always resulted in error.

**Comment by WooMai** [comment]
This issue should already be fixed. Thanks for the feedback.

Issues for this repository are not monitored.
If you have additional questions, don't hesitate to contact xiaomai@wmlabs.net for a quicker response.
